#pragma once
#include <functional>
#include <memory>
#include "cortrix/spc/spc_task.h"
#include "cortrix/metadata/rule_based_metadata_generator.h"  // doc-level metadata block (stateless, owned)
#include "cortrix/spc/data_cleaner.h"                         // dedup + anomaly detection (owned)
#include "cortrix/scoring/semantic_scorer.h"                  // write-time processing_level + semantic_score (owned)

namespace cortrix {

namespace resource { class NamespaceFacade; }  // D3.5 wire⑤: Process runs over the façade
namespace spc { class DocumentParserFactory; class ISpcEnricher; class EnricherChain; struct ParsedDoc; }  // parser (ParsedDoc) + enricher (injected) + I1 chain
namespace chunker { class ParentChildChunker; } // parent-child chunker
namespace async { struct SubmitRequest; }       // doc-summary enqueue seam payload
namespace retrieval { class SparseIndexRegistry; }  // per-NS SPLADE index owner

class OnnxEmbedder;
class BlockAssembler;

/// Processes a single SPCTask through the full SPC pipeline:
/// Parse (structured) -> Chunk (parent-child) -> Embed -> Assemble -> Store.
///
/// Document ingest runs the structured parser
/// (cortrix::spc::DocumentParserFactory::ParseDocument → ParsedDoc{ParsedPage[]})
/// → ParentChildChunker (ChunkerOutput{parents, children}) → unified write:
/// parents into the `parents` table (store.parent_insert) + children into the
/// unified `blocks` table (assembler.AssembleChild + store.block_insert), all in
/// one WriteCoordinator transaction. OCR / VLM are owned internally by the parser (no
/// OcrProcessor / VisionLlmProcessor here — DECISION X). The memory-session path
/// bypasses parse + chunker and writes one flat block via the assembler's
/// flat Assemble().
///
/// After chunking (parse → chunk → metadata), one doc-level
/// Metadata Block (block_type = kBlockMeta = 8) is generated by the rule-based
/// generator and written into the same `blocks` table + same write txn (L3: embedded
/// into P-HNSW per D7). One META per doc, enforced by idx_blocks_meta_doc.
class SPCPipeline {
public:
    SPCPipeline(cortrix::spc::DocumentParserFactory& parser_factory,
                cortrix::chunker::ParentChildChunker& chunker,
                OnnxEmbedder& embedder,
                BlockAssembler& assembler,
                cortrix::spc::ISpcEnricher& enricher);

    /// Process a single task end-to-end over the per-request namespace façade.
    /// L2/L3 writes are transactional (C2): assemble all child blocks (block_id =
    /// HashChildIdToBlockId(child_id)) → BeginWrite(writes_blob=false) → AddPoints
    /// (L3) → parent_insert (per parent) → block_insert (per child) → Commit,
    /// Rollback on any failure (design §10.2).
    /// @return 0 = success, -1 = error (task.error_message filled)
    int Process(SPCTask& task, resource::NamespaceFacade& facade);

    /// Post-parse entry: runs Stage 3+ (Chunk → META → 
    /// enrich → embed → assemble → write → OnDocumentWritten) over an already-parsed
    /// doc. Process() delegates here right after Stage 2; the async task path
    /// (DocumentProcessor, which already F06-parsed with per-page progress/cancel) calls
    /// it directly to avoid re-parsing. `d` is non-const: d.pages is moved into the chunker.
    /// @return 0 = success, -1 = error (task.error_message filled)
    int ProcessParsed(cortrix::spc::ParsedDoc& d, SPCTask& task,
                      resource::NamespaceFacade& facade);

    /// Install the per-NS CleaningConfig
    /// resolver. When set, each Process/ProcessParsed resolves the effective
    /// CleaningConfig for the task's namespace (global ← namespaces.cleaning_config,
    /// §3.4 three-layer; V1.0 has no request layer) and applies it to the owned
    /// DataCleaner before dedup/anomaly. Bootstrap wires it to
    /// INSRouter::GetNamespace(ns).cleaning_config + the global defaults
    /// (ResolveCleaningConfig); the NS metadata lives in the catalog, which the
    /// per-request NamespaceFacade does not expose, so this seam (not the façade)
    /// carries it. Unset / nullptr = feature off: the DataCleaner keeps its default
    /// CleaningConfig{} (standalone behavior, backward compatible). The bound
    /// callable must outlive the pipeline (bootstrap owns the router + config).
    void SetCleaningConfigResolver(
        std::function<cortrix::spc::CleaningConfig(const std::string& ns_id)> fn);

    /// Install the doc-summary enqueue seam. When set
    /// (production wires it to TaskScheduler::Enqueue via the adapter), a
    /// successfully written full document fires OnDocumentWritten → enqueue a
    /// kTaskDocSummary task. Unset / nullptr = feature off (no doc-summary task;
    /// doc-discovery degrades to the FTS5 fallback). The real scheduler wiring in main is
    /// a separate step because scheduler productization is handled independently.
    void SetDocSummaryEnqueue(std::function<void(const async::SubmitRequest&)> fn);

    /// Install the ISpcEnricher chain (enrich → contextualize → HyPE, fail-soft
    /// serial). When set, the Stage-3.6 enrich step runs the whole chain (
    /// entities/summary + contextualized_* re-embedding + hype_question
    /// Block generation) instead of the single injected `enricher_`. Unset =
    /// backward-compatible single-enricher behavior (the ctor `enricher_` only).
    /// The chain must outlive the pipeline (bootstrap owns it). Non-owning pointer
    /// (the chain is shared with no other consumer; nullptr = feature off).
    void SetEnricherChain(cortrix::spc::EnricherChain* chain);

    /// Install the per-NS SPLADE inverted-index registry. When set,
    /// the Stage-4 child embed switches to EmbedBatchWithSparse and the Stage-5
    /// write phase persists each child's sparse vector to blocks.sparse_vec AND
    /// indexes it into the registry's per-NS inverted index (so the sparse read-path
    /// sparse route — Wave Q — has live postings). The registry must outlive the
    /// pipeline (bootstrap owns it, shared with the query wiring). Non-owning;
    /// nullptr = feature off (children embed dense-only, sparse_vec stays NULL).
    void SetSparseIndexRegistry(cortrix::retrieval::SparseIndexRegistry* registry);

    /// [⑤c] Document-written hook: if the doc-summary seam is installed, enqueue a
    /// kTaskDocSummary task for (doc_id, ns_id). Called at the end of the full-doc
    /// success path; a no-op when the seam is unset. Public for direct unit testing.
    void OnDocumentWritten(const std::string& doc_id, const std::string& ns_id);

private:
    cortrix::spc::DocumentParserFactory& parser_factory_;
    cortrix::chunker::ParentChildChunker& chunker_;
    OnnxEmbedder& embedder_;
    BlockAssembler& assembler_;
    // NER+Summary enricher (injected). Runs after META gen and
    // before embed (ARCH §2.3 SoT). NullEnricher (IsAvailable()==false) short-circuits;
    // the production factory injects CreateEnricher(config) (LlmEnricher if configured).
    cortrix::spc::ISpcEnricher& enricher_;
    // Optional enricher chain (enrich → contextualize → HyPE). When non-null it
    // supersedes `enricher_` for the Stage-3.6 enrich step. Non-owning (bootstrap
    // owns the chain + its enrichers); nullptr = single-enricher path.
    cortrix::spc::EnricherChain* enricher_chain_ = nullptr;
    // Optional per-NS SPLADE inverted-index registry. When non-null the
    // child embed produces sparse vectors and the write phase persists +
    // indexes them. Non-owning (bootstrap owns it, shared with the query wiring);
    // nullptr = dense-only (sparse_vec stays NULL, read path degrades to dense+FTS5).
    cortrix::retrieval::SparseIndexRegistry* sparse_registry_ = nullptr;
    // Doc-level metadata generator. Owned (not injected): stateless, default-
    // constructible, and the sole V1.0 impl (D4 lock) — so no ctor wiring / DI is
    // needed and the SPCPipeline ctor signature is unchanged.
    cortrix::metadata::RuleBasedMetadataGenerator meta_generator_;
    // Data cleaner (dedup + anomaly detection). Owned with the default
    // CleaningConfig; the per-task NS-override (§3.4) is applied via SetConfig from
    // cleaning_config_resolver_ when that seam is installed. The operation-log audit sink is
    // nullable (left null here) — so no ctor ripple.
    cortrix::spc::DataCleaner data_cleaner_{cortrix::spc::CleaningConfig{}};
    // Optional per-NS CleaningConfig resolver (nullable = feature off →
    // default CleaningConfig{}). Production wires it to INSRouter::GetNamespace +
    // ResolveCleaningConfig (bootstrap); given a ns_id it returns the resolved
    // effective config, applied to data_cleaner_ before each cleaning run.
    std::function<cortrix::spc::CleaningConfig(const std::string& ns_id)>
        cleaning_config_resolver_;
    // Semantic scorer (write-time processing_level + semantic_score). Owned:
    // stateless, default-constructible, sole V1 impl — so no ctor wiring / DI needed.
    cortrix::scoring::SemanticScorer scorer_;
    // Doc-summary enqueue seam (nullable = feature off). Production wires
    // it to TaskScheduler::Enqueue; unset leaves OnDocumentWritten a no-op.
    std::function<void(const async::SubmitRequest&)> doc_summary_enqueue_;
};

}  // namespace cortrix
