"""Cortrix Python SDK — semantic storage for AI agents.

Public surface::

    from cortrix import Cortrix, AsyncCortrix
    from cortrix import CortrixError, AuthenticationError, RateLimitError, ...
"""

from __future__ import annotations

from ._async_client import AsyncCortrix
from ._client import Cortrix
from ._constants import SDK_VERSION
from ._exceptions import (
    # base + L1 (12)
    AuthenticationError,
    ConflictError,
    ConnectionError,
    CortrixError,
    ErrorCategory,
    FeatureNotAvailableError,
    ForbiddenError,
    InternalServerError,
    InvalidRequestError,
    NotFoundError,
    PayloadTooLargeError,
    RateLimitError,
    ServiceUnavailableError,
    TimeoutError,
    # L2 (23 concrete)
    AuthAdminRequiredError,
    AuthBcryptTimeoutError,
    AuthBootstrapTokenInvalidError,
    AuthEmailAlreadyExistsError,
    AuthEmailSendFailedError,
    AuthInvalidApiKeyError,
    AuthInvalidCredentialsError,
    AuthInvalidResetCodeError,
    AuthJwtInitFailedError,
    AuthTokenExpiredError,
    AuthTokenVerificationFailedError,
    CsrfMismatchError,
    PgcortrixInvalidFilterError,
    RagFusionExpandTimeoutError,
    CragEvaluationFailedError,
    DocSummaryFailedError,
    AgentToolNotFoundError,
    LlmCircuitOpenError,
    MemoryExtractionFailedError,
    NamespaceNotFoundError,
    QuotaExceededError,
    StoreDbError,
    StoreNotFoundError,
)
from .types import (
    AgentLlmConfig,
    AgentSession,
    ApiKey,
    Document,
    DocumentList,
    DocumentProgress,
    DocumentTask,
    GcStatus,
    LoginResponse,
    Memory,
    MemoryCreateAck,
    MemoryDeleteAck,
    MemoryEditAck,
    MemoryList,
    MemorySearchResponse,
    MemorySearchResultItem,
    Namespace,
    NamespaceList,
    NsStats,
    Quota,
    QueryResult,
    QueryResultItem,
    SearchResults,
    SqlResult,
    SyncStatus,
    Tenant,
    TenantMember,
    User,
    WatchEvent,
    Watcher,
    WatcherList,
)

__version__ = SDK_VERSION

__all__ = [
    "Cortrix",
    "AsyncCortrix",
    "__version__",
    # exceptions — base + L1
    "CortrixError",
    "ErrorCategory",
    "InvalidRequestError",
    "AuthenticationError",
    "ForbiddenError",
    "NotFoundError",
    "ConflictError",
    "PayloadTooLargeError",
    "RateLimitError",
    "InternalServerError",
    "ServiceUnavailableError",
    "FeatureNotAvailableError",
    "ConnectionError",
    "TimeoutError",
    # exceptions — L2
    "NamespaceNotFoundError",
    "AuthEmailAlreadyExistsError",
    "AuthInvalidCredentialsError",
    "AuthInvalidResetCodeError",
    "AuthTokenExpiredError",
    "AuthBootstrapTokenInvalidError",
    "AuthInvalidApiKeyError",
    "AuthAdminRequiredError",
    "AuthTokenVerificationFailedError",
    "AuthEmailSendFailedError",
    "AuthBcryptTimeoutError",
    "AuthJwtInitFailedError",
    "StoreNotFoundError",
    "StoreDbError",
    "PgcortrixInvalidFilterError",
    "RagFusionExpandTimeoutError",
    "CragEvaluationFailedError",
    "DocSummaryFailedError",
    "AgentToolNotFoundError",
    "MemoryExtractionFailedError",
    "LlmCircuitOpenError",
    "QuotaExceededError",
    "CsrfMismatchError",
    # types
    "Document",
    "DocumentProgress",
    "DocumentTask",
    "DocumentList",
    "Namespace",
    "NamespaceList",
    "QueryResult",
    "QueryResultItem",
    "SearchResults",
    "Memory",
    "MemoryCreateAck",
    "MemoryDeleteAck",
    "MemoryEditAck",
    "MemoryList",
    "MemorySearchResponse",
    "MemorySearchResultItem",
    "SqlResult",
    "SyncStatus",
    "Watcher",
    "WatcherList",
    "WatchEvent",
    "LoginResponse",
    "User",
    "ApiKey",
    "Tenant",
    "TenantMember",
    "Quota",
    "GcStatus",
    "NsStats",
    "AgentLlmConfig",
    "AgentSession",
]
